[package]
name = "coral_reef"
version = "0.1.0"
authors = ["Alyce Ge <alyce.ge@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand= "0.7.3"
structopt="0.3"
rand_distr="0.3.0"
